theme: jekyll-theme-cayman
title: How to install dictionary in termux
description: In this article you will got to know ,how to install dictionary in termux
google-site-verification: googlecde2663039a50a6d
